
INSERT INTO PROVEEDOR (NOMBRE) VALUES ('Walmart');
INSERT INTO PROVEEDOR (NOMBRE) VALUES ('Carrefour');
INSERT INTO PROVEEDOR (NOMBRE) VALUES ('Vea');

INSERT INTO TIPO_ARTICULO (NOMBRE) VALUES ('LACTEOS');
INSERT INTO TIPO_ARTICULO (NOMBRE) VALUES ('PANADERIA');
INSERT INTO TIPO_ARTICULO (NOMBRE) VALUES ('FRUTAS');
INSERT INTO TIPO_ARTICULO (NOMBRE) VALUES ('LIMPIEZA');


INSERT INTO DEMANDA (CANTIDAD, PRONOSTICO, ID_ARTICULO, MES_PERIODO_FIN, MES_PERIODO_INICIO) VALUES (125, 120, 1,  '2024-01-30',  '2024-01-01');
INSERT INTO DEMANDA (CANTIDAD, PRONOSTICO, ID_ARTICULO, MES_PERIODO_FIN, MES_PERIODO_INICIO) VALUES (100, 100, 1,  '2024-02-30',  '2024-02-01');
INSERT INTO DEMANDA (CANTIDAD, PRONOSTICO, ID_ARTICULO, MES_PERIODO_FIN, MES_PERIODO_INICIO) VALUES (125, 120, 1,  '2024-03-30',  '2024-03-01');
INSERT INTO DEMANDA (CANTIDAD, PRONOSTICO, ID_ARTICULO, MES_PERIODO_FIN, MES_PERIODO_INICIO) VALUES (100, 100, 1,  '2024-04-30',  '2024-04-01');
INSERT INTO DEMANDA (CANTIDAD, PRONOSTICO, ID_ARTICULO, MES_PERIODO_FIN, MES_PERIODO_INICIO) VALUES (125, 120, 1, '2024-05-30',  '2024-05-01');
INSERT INTO DEMANDA (CANTIDAD, PRONOSTICO, ID_ARTICULO, MES_PERIODO_FIN, MES_PERIODO_INICIO) VALUES (100, 100, 1, '2024-06-30',  '2024-06-01');

INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Leche Entera 1L', 'Leche pasteurizada entera en envase de 1 litro', 'LACTEOS', 2.99, 8, 500);
INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Pan Integral', 'Pan de trigo integral, ideal para una dieta balanceada', 'PANADERIA', 1.49, 10, 300);
INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Manzanas Gala', 'Manzanas frescas de la variedad Gala, caja de 1kg', 'FRUTAS', 3.99, 6, 200);
INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Jabón en Barra', 'Jabón neutro en barra para uso diario', 'LIMPIEZA', 0.99, 12, 1000);

INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Leche Entera 1L', 'Leche pasteurizada entera en envase de 1 litro', 'LACTEOS', 2.99, 8, 500);
INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Pan Integral', 'Pan de trigo integral, ideal para una dieta balanceada', 'PANADERIA', 1.49, 10, 300);
INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Manzanas Gala', 'Manzanas frescas de la variedad Gala, caja de 1kg', 'FRUTAS', 3.99, 6, 200);
INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Jabón en Barra', 'Jabón neutro en barra para uso diario', 'LIMPIEZA', 0.99, 12, 1000);