
INSERT INTO PROVEEDOR (NOMBRE) VALUES ('Walmart');
INSERT INTO PROVEEDOR (NOMBRE) VALUES ('Carrefour');
INSERT INTO PROVEEDOR (NOMBRE) VALUES ('Vea');
INSERT INTO PROVEEDOR (NOMBRE) VALUES ('ChangoMas');

INSERT INTO TIPO_ARTICULO (NOMBRE) VALUES ('LACTEOS');
INSERT INTO TIPO_ARTICULO (NOMBRE) VALUES ('PANADERIA');
INSERT INTO TIPO_ARTICULO (NOMBRE) VALUES ('FRUTAS');
INSERT INTO TIPO_ARTICULO (NOMBRE) VALUES ('LIMPIEZA');
INSERT INTO TIPO_ARTICULO (NOMBRE) VALUES ('BEBIDA');

INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Leche Entera 1L', 'Leche pasteurizada entera en envase de 1 litro', 'LACTEOS', 2.99, 8, 500);
INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Pan Integral', 'Pan de trigo integral, ideal para una dieta balanceada', 'PANADERIA', 1.49, 10, 300);
INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Manzanas Gala', 'Manzanas frescas de la variedad Gala, caja de 1kg', 'FRUTAS', 3.99, 6, 200);
INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Jabón en Barra', 'Jabón neutro en barra para uso diario', 'LIMPIEZA', 0.99, 12, 1000);

INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Cerveza', 'Cerveza artesanal', 'BEBIDA', 0.99, 12, 10);

INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Harina', 'Harina 0000', 'PANADERIA', 15, 12, 10);

INSERT INTO ARTICULO (NOMBRE, DESCRIPCION, COD_TIPO_ARTICULO, PRECIO, TASA_ROTACION, STOCK)
VALUES ('Harina', 'Harina 0000', 'PANADERIA', 15, 12, 10);

INSERT INTO VENTA (MONTO_TOTAL)
VALUES
    (200.0),
    (200.0),
    (200.0),
    (200.0),
    (200.0);

INSERT INTO ARTICULO_PROVEEDOR (COSTO_PEDIDO, LOTE_OPTIMO, PUNTO_PEDIDO, STOCK_SEGURIDAD, TIEMPO_ENTREGA, ID_ARTICULO,
                                ID_PROVEEDOR, MODELO) VALUES (10, 9, 5, 11000, 10, 4, 'Vea', 'lote-fijo');

INSERT INTO ARTICULO_VENTA (ANO, CANTIDAD_ARTICULOS, DIA, MES, ARTICULO_ID, VENTA_ID)
VALUES
    (2024, 100, 17, 7, 1, 1),
    (2024, 150, 23, 8, 2, 2),
    (2024, 80,  5,  5, 3, 3),
    (2024, 120, 12, 4, 1, 4),
    (2024, 200, 28, 5, 2, 5),
    (2023, 80,  15, 1, 3, 1),
    (2022, 120, 20, 2, 1, 2),
    (2021, 150, 25, 7, 2, 3),
    (2020, 200, 10, 8, 3, 4);